import { createHash } from 'node:crypto';

const BEGIN = '<!-- @repospec-generated';
const END = '-->';

/** A generated file's parsed managed header and body. */
export interface ManagedFile {
  /** Protocol version recorded in the header, if present. */
  protocol?: string;
  /** Checksum recorded in the header, if present. */
  checksum?: string;
  /** The body following the header. */
  body: string;
}

/**
 * Compute the content checksum used to detect out-of-band edits.
 *
 * @param body - The generated body (without the managed header).
 * @returns A `sha256:<hex>` checksum string.
 */
export function checksum(body: string): string {
  return `sha256:${createHash('sha256').update(body, 'utf8').digest('hex')}`;
}

/**
 * Wrap a generated body with the managed header (ADR-0004): a clear notice, the
 * source protocol version, and a checksum of the body.
 *
 * @param body - The generated content to wrap.
 * @param protocolVersion - The protocol version that produced it.
 * @returns The full file contents to write.
 */
export function wrapManaged(body: string, protocolVersion: string): string {
  const header = [
    BEGIN,
    'This file is generated by Repospec from .repospec/. Do not edit it directly —',
    'edit the .repospec/ directory and run `repospec sync`.',
    `protocol: ${protocolVersion}`,
    `checksum: ${checksum(body)}`,
    END,
  ].join('\n');
  return `${header}\n\n${body}`;
}

/**
 * Parse a managed file back into its header fields and body.
 *
 * @param text - The on-disk file contents.
 * @returns The parsed managed file, or `null` if it is not Repospec-managed.
 */
export function parseManaged(text: string): ManagedFile | null {
  if (!text.startsWith(BEGIN)) return null;
  const end = text.indexOf(END);
  if (end === -1) return null;
  const header = text.slice(BEGIN.length, end);
  const body = text.slice(end + END.length).replace(/^\n+/, '');
  const protocol = /protocol:\s*(\S+)/.exec(header)?.[1];
  const checksumValue = /checksum:\s*(\S+)/.exec(header)?.[1];
  return { protocol, checksum: checksumValue, body };
}

/**
 * Report whether a managed file has been edited out-of-band (its body no longer
 * matches the checksum recorded in its header).
 *
 * @param managed - A parsed managed file.
 * @returns `true` if the body was modified after generation.
 */
export function isModified(managed: ManagedFile): boolean {
  if (!managed.checksum) return false;
  return checksum(managed.body) !== managed.checksum;
}
