// A tiny example plugin: generates a compliance summary from the repo model.
export default async ({ repo }) => ({
  outputs: [
    {
      path: 'COMPLIANCE.md',
      body: `# Compliance — ${repo.project.project.name}\n\nGenerated by the acme-compliance-pack plugin from .repospec/.\n`,
    },
  ],
});
