#!/usr/bin/env python3
"""repospec build — compile a project's .repospec/ directory into AGENTS.md.

Reference implementation of the Repospec Protocol build step. The .repospec/ directory
is the human-authored source of truth; AGENTS.md is the generated artifact that
coding agents actually read. This keeps them in sync.

Usage:
    repospec_build.py [PROJECT_DIR] [--check]

PROJECT_DIR defaults to "." and must contain a .repospec/ directory.
--check compiles in memory and exits non-zero if the on-disk AGENTS.md differs,
without writing anything. Use it in CI to catch a stale AGENTS.md.

Requires PyYAML (pip install pyyaml).
"""
import sys
import os
import re
import difflib

try:
    import yaml
except ImportError:
    sys.exit("repospec build: requires PyYAML  ->  pip install pyyaml")

GEN_HEADER = (
    "<!--\n"
    "  GENERATED BY REPOSPEC - do not hand-edit.\n"
    "  Source: .repospec/   .   Regenerate: `repospec build`\n"
    "-->\n"
)


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def parse_frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---\n?(.*)$", text, re.S)
    if not m:
        return {}, text
    return yaml.safe_load(m.group(1)) or {}, m.group(2)


def strip_h1(md):
    return re.sub(r"^\s*#\s+.*\n+", "", md, count=1).strip()


def sentence(text):
    text = text.strip()
    return text[0].upper() + text[1:] if text else text


def compile_agents(project_dir):
    repospec = os.path.join(project_dir, ".repospec")
    if not os.path.isdir(repospec):
        sys.exit(f"repospec build: no .repospec/ directory in {project_dir!r}")

    proj = yaml.safe_load(read(os.path.join(repospec, "project.yaml"))) or {}
    out = [GEN_HEADER, f"# {proj.get('name', 'project')}\n"]

    # --- identity -------------------------------------------------------
    ident = " ".join(p for p in [proj.get("summary", "").strip(),
                                 proj.get("users", "").strip()] if p)
    if ident:
        out.append(ident + "\n")
    meta = []
    if proj.get("stack"):
        meta.append("Stack: " + " / ".join(str(v) for v in proj["stack"].values()))
    if proj.get("deploy"):
        meta.append("Deploy: " + " via ".join(str(v) for v in proj["deploy"].values()))
    if proj.get("compliance"):
        meta.append("Compliance: " + ", ".join(proj["compliance"]))
    if meta:
        out.append(". ".join(meta) + ".\n")

    # --- constitution ---------------------------------------------------
    const = os.path.join(repospec, "constitution.md")
    if os.path.exists(const):
        out.append("## Constitution (non-negotiable)\n")
        out.append(strip_h1(read(const)) + "\n")

    # --- roles ----------------------------------------------------------
    roles = proj.get("roles", []) or []
    if roles:
        out.append("## Roles\n")
        out.append("Work moves through defined roles, each with bounded authority. "
                   "Operate as exactly one role at a time.\n")
        for r in roles:
            rp = os.path.join(repospec, "agents", f"{r}.md")
            if not os.path.exists(rp):
                out.append(f"- **{r}** - (definition missing: agents/{r}.md)")
                continue
            fm, _ = parse_frontmatter(read(rp))
            line = f"- **{r}**"
            if fm.get("owns"):
                line += f" - owns {fm['owns'].strip()}."
            if fm.get("authority"):
                line += f" {sentence(fm['authority'])}."
            out.append(line)
        out.append("\nFull definitions: `.repospec/agents/`.\n")

    # --- workflow -------------------------------------------------------
    wf_path = os.path.join(repospec, "workflow.md")
    if os.path.exists(wf_path):
        wf = read(wf_path)
        out.append("## Workflow\n")
        arrow = next((ln.strip() for ln in wf.splitlines() if "\u2192" in ln), "")
        gates = []
        for ln in wf.splitlines():
            if ln.strip().startswith("|"):
                cells = [c.strip() for c in ln.strip().strip("|").split("|")]
                if len(cells) >= 2 and cells[-1].lower() == "yes":
                    gates.append(cells[0])
        if arrow:
            out.append(arrow + ".")
        gate_txt = (f"Steps can't be skipped; human gates ({', '.join(gates)}) "
                    "can't be auto-cleared. ") if gates else "Steps can't be skipped. "
        out.append(gate_txt + "Details: `.repospec/workflow.md`.\n")

    # --- rules ----------------------------------------------------------
    rules_dir = os.path.join(repospec, "rules")
    if os.path.isdir(rules_dir):
        files = sorted(f for f in os.listdir(rules_dir) if f.endswith(".md"))
        if files:
            out.append("## Rules\n")
            for f in files:
                out.append(f"- {os.path.splitext(f)[0].capitalize()}: `.repospec/rules/{f}`")
            out.append("")

    # --- memory ---------------------------------------------------------
    has_dec = os.path.isdir(os.path.join(repospec, "decisions"))
    has_hist = os.path.isdir(os.path.join(repospec, "history"))
    if has_dec or has_hist:
        out.append("## Memory\n")
        if has_dec:
            out.append("- Decisions - why the system is the way it is: `.repospec/decisions/`")
        if has_hist:
            out.append("- History - how it got here: `.repospec/history/`")
        out.append("\nSettled decisions are not re-litigated. "
                   "Read `decisions/` before proposing architectural change.\n")

    text = "\n".join(out)
    text = re.sub(r"\n{3,}", "\n\n", text).rstrip() + "\n"
    return text


def main():
    args = sys.argv[1:]
    check = "--check" in args
    rest = [a for a in args if a != "--check"]
    project_dir = rest[0] if rest else "."

    compiled = compile_agents(project_dir)
    target = os.path.join(project_dir, "AGENTS.md")

    if check:
        current = read(target) if os.path.exists(target) else ""
        if current != compiled:
            sys.stderr.write("repospec build --check: AGENTS.md is stale. Run `repospec build`.\n\n")
            sys.stderr.writelines(difflib.unified_diff(
                current.splitlines(True), compiled.splitlines(True),
                fromfile="AGENTS.md (committed)", tofile="AGENTS.md (expected)"))
            sys.exit(1)
        print("repospec build --check: AGENTS.md is up to date.")
        return

    with open(target, "w", encoding="utf-8") as f:
        f.write(compiled)
    print(f"repospec build: wrote {target}")


if __name__ == "__main__":
    main()
